version: '2'
services:
  schoolarapp-mongodb:
    image: mongo:4.2.3
    environment:
      - MONGO_INITDB_DATABASE=schoolarapp
      - MONGO_INITDB_ROOT_USERNAME=sa
      - MONGO_INITDB_ROOT_PASSWORD=yourStrong(!)Password
    ports:
      - '27018:27017'
    # volumes:
    #     - ~/volumes/jhipster/schoolarapp/mongodb/:/data/db/
